import { Header } from "@/partials/Header";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Company } from "@/partials/Company";
import { ReactElement } from "react";
import { About } from "@/partials/About";
import { Contact } from "@/partials/contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): ReactElement {
  return (
    <>
      <Head>
        <title>AGÁ Empreendimentos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Company />
        <About />
        <Contact />
      </main>
    </>
  );
}
